steps:

- id: 'Instalando aplicativo GO...'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'app']
  env: ['GOPATH=.']

- id: 'Executando Testes...'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v','./...']
  env: ['GOPATH=.']

- id: "Building image from Dockerfile"
  name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/golang-loop:$SHORT_SHA", "-f", "Dockerfile", "."]

  - id: "Pushing image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/golang-loop:$SHORT_SHA"]

  - id: "Ajustando arquivo de deployment do k8s"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        sed "s#img-go-hpa-deployment#gcr.io/$PROJECT_ID/golang-loop:$SHORT_SHA#g" ./k8s/deployment.yml > ./k8s/deployment-new.yml;
        cat ./k8s/deployment-new.yml;

  - id: "Deploy k8s"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "k8s/deployment-new.yml"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-golang-hpa"


